#pragma once
// =====================================================================
// Curated cheat/macro identifier database for jar-level static analysis
// (used by ModsScan.h). Ported and deduplicated from the MeowModAnalyzer
// PowerShell tool's $cheatStrings / $suspiciousPatterns lists, ASCII
// entries only -- fullwidth-Unicode evasion variants (e.g. the
// "\uFF21-\uFF3A" lookalike-character tricks some clients use to dodge
// literal string matching) are handled generically in ModsScan.h by
// normalizing fullwidth characters back to ASCII before matching, rather
// than needing a hardcoded fullwidth twin for every entry here.
// =====================================================================
#include <string>
#include <vector>

inline const std::vector<std::string> jarContentStrings = {
    "AutoCrystal",
    "autocrystal",
    "auto crystal",
    "cw crystal",
    "JDWP.VirtualMachine.AllModules",
    "dontPlaceCrystal",
    "dontBreakCrystal",
    "AutoHitCrystal",
    "autohitcrystal",
    "canPlaceCrystalServer",
    "healPotSlot",
    "AutoAnchor",
    "autoanchor",
    "auto anchor",
    "DoubleAnchor",
    "HasAnchor",
    "anchortweaks",
    "anchor macro",
    "safe anchor",
    "safeanchor",
    "SafeAnchor",
    "AirAnchor",
    "anchorMacro",
    "AutoTotem",
    "autototem",
    "auto totem",
    "InventoryTotem",
    "inventorytotem",
    "HoverTotem",
    "hover totem",
    "legittotem",
    "AutoPot",
    "autopot",
    "auto pot",
    "speedPotSlot",
    "strengthPotSlot",
    "AutoArmor",
    "autoarmor",
    "auto armor",
    "AutoPotRefill",
    "preventSwordBlockBreaking",
    "preventSwordBlockAttack",
    "ShieldDisabler",
    "ShieldBreaker",
    "Breaking shield with axe...",
    "AutoDoubleHand",
    "autodoublehand",
    "auto double hand",
    "AutoClicker",
    "Failed to switch to mace after axe!",
    "AutoMace",
    "MaceSwap",
    "SpearSwap",
    "StunSlam",
    "Donut",
    "JumpReset",
    "axespam",
    "axe spam",
    "findKnockbackSword",
    "attackRegisteredThisClick",
    "AimAssist",
    "aimassist",
    "aim assist",
    "triggerbot",
    "trigger bot",
    "Silent Rotations",
    "SilentRotations",
    "FakeInv",
    "swapBackToOriginalSlot",
    "FakeLag",
    "pingspoof",
    "ping spoof",
    "fakePunch",
    "Fake Punch",
    "mace_swap",
    "quick_strike",
    "macro_198",
    "stun_slam",
    "safe_anchor",
    "double_anchor",
    "auto_pot_refill",
    "walksy_optimizer",
    "key_pearl",
    "aim_assist",
    "auto_neth_pot",
    "auto_dtap",
    "trigger_bot",
    "auto_web",
    "DOUBLE_ESCAPE",
    "DOUBLE_RIGHTCLICK_FIRST",
    "DOUBLE_RIGHTCLICK_SECOND",
    "POST_CYCLE_DELAY",
    "PLACE_OBI",
    "WAIT_OBI",
    "PLACE_CRYSTAL",
    "BREAK_CRYSTAL",
    "ROTATING_DOWN",
    "ROTATING_BACK",
    "REFILLING",
    "PLANTING",
    "BONEMEALING",
    "AnchorAction",
    "Places two anchors for massive damage",
    "REOFFHAND_TOTEM",
    "webmacro",
    "web macro",
    "AntiWeb",
    "AutoWeb",
    "lvstrng",
    "dqrkis",
    "selfdestruct",
    "self destruct",
    "WalksyCrystalOptimizerMod",
    "WalksyOptimizer",
    "WalskyOptimizer",
    "autoCrystalPlaceClock",
    "AutoFirework",
    "ElytraSwap",
    "FastXP",
    "FastExp",
    "NoJumpDelay",
    "PackSpoof",
    "Antiknockback",
    "catlean",
    "AuthBypass",
    "obfuscatedAuth",
    "LicenseCheckMixin",
    "BaseFinder",
    "invsee",
    "ItemExploit",
    "FreezePlayer",
    "LWFH Crystal",
    "KeyPearl",
    "LootYeeter",
    "FastPlace",
    "AutoBreach",
    "setBlockBreakingCooldown",
    "getBlockBreakingCooldown",
    "blockBreakingCooldown",
    "onBlockBreaking",
    "setItemUseCooldown",
    "invokeDoAttack",
    "invokeDoItemUse",
    "invokeOnMouseButton",
    "onPushOutOfBlocks",
    "onIsGlowing",
    "Automatically switches to sword when hitting with totem",
    "arrayOfString",
    "POT_CHEATS",
    "Dqrkis Client",
    "Entity.isGlowing",
    "Activate Key",
    "Click Simulation",
    "On RMB",
    "No Count Glitch",
    "No Bounce",
    "NoBounce",
    "Place Delay",
    "Break Delay",
    "Place Chance",
    "Break Chance",
    "Stop On Kill",
    "damagetick",
    "Anti Weakness",
    "Particle Chance",
    "Trigger Key",
    "Switch Delay",
    "Totem Slot",
    "Smooth Rotations",
    "Rotation Speed",
    "Use Easing",
    "Easing Strength",
    "While Use",
    "Stop on Kill",
    "Glowstone Delay",
    "Glowstone Chance",
    "Explode Delay",
    "Explode Chance",
    "Explode Slot",
    "Only Charge",
    "Anchor Macro",
    "Reach Distance",
    "Min Height",
    "Min Fall Speed",
    "Attack Delay",
    "Breach Delay",
    "Require Elytra",
    "Auto Switch Back",
    "Check Line of Sight",
    "Only When Falling",
    "Require Crit",
    "Show Status Display",
    "Stop On Crystal",
    "Check Shield",
    "On Pop",
    "Predict Damage",
    "On Ground",
    "Check Players",
    "Predict Crystals",
    "Check Aim",
    "Check Items",
    "Activates Above",
    "Blatant",
    "Force Totem",
    "Stay Open For",
    "Auto Inventory Totem",
    "Only On Pop",
    "Vertical Speed",
    "Hover Totem",
    "Swap Speed",
    "Strict One-Tick",
    "Mace Priority",
    "Min Totems",
    "Min Pearls",
    "Totem First",
    "Drop Interval",
    "Random Pattern",
    "Loot Yeeter",
    "Horizontal Aim Speed",
    "Vertical Aim Speed",
    "Include Head",
    "Web Delay",
    "Holding Web",
    "Not When Affects Player",
    "Hit Delay",
    "Require Hold Axe",
    "placeInterval",
    "breakInterval",
    "stopOnKill",
    "activateOnRightClick",
    "holdCrystal",
    "Macro Key",
    "KillAura",
    "ClickAura",
    "MultiAura",
    "ForceField",
    "LegitAura",
    "AimBot",
    "AutoAim",
    "SilentAim",
    "AimLock",
    "HeadSnap",
    "CrystalAura",
    "AnchorAura",
    "AnchorFill",
    "AnchorPlace",
    "BedAura",
    "AutoBed",
    "BedBomb",
    "BedPlace",
    "BowAimbot",
    "BowSpam",
    "AutoBow",
    "AutoCrit",
    "CritBypass",
    "AlwaysCrit",
    "CriticalHit",
    "ReachHack",
    "ExtendReach",
    "LongReach",
    "HitboxExpand",
    "AntiKB",
    "NoKnockback",
    "GrimVelocity",
    "GrimDisabler",
    "VelocitySpoof",
    "KBReduce",
    "OffhandTotem",
    "TotemSwitch",
    "AutoWeapon",
    "AutoSword",
    "AutoCity",
    "Burrow",
    "SelfTrap",
    "HoleFiller",
    "AntiSurround",
    "AntiBurrow",
    "WTap",
    "TargetStrafe",
    "AutoGap",
    "AutoPearl",
    "FlyHack",
    "CreativeFlight",
    "BoatFly",
    "PacketFly",
    "AirJump",
    "SpeedHack",
    "BHop",
    "BunnyHop",
    "AntiFall",
    "NoFallDamage",
    "SafeFall",
    "StepHack",
    "FastClimb",
    "AutoStep",
    "HighStep",
    "WaterWalk",
    "LiquidWalk",
    "LavaWalk",
    "NoSlow",
    "NoSlowdown",
    "NoWeb",
    "NoSoulSand",
    "WallHack",
    "ElytraSpeed",
    "InstantElytra",
    "ScaffoldWalk",
    "FastBridge",
    "BuildHelper",
    "AutoBridge",
    "Nuker",
    "NukerLegit",
    "InstantBreak",
    "GhostHand",
    "NoSwing",
    "PlaceAssist",
    "AirPlace",
    "AutoPlace",
    "InstantPlace",
    "PlayerESP",
    "MobESP",
    "ItemESP",
    "StorageESP",
    "ChestESP",
    "Tracers",
    "NameTagsHack",
    "XRayHack",
    "OreFinder",
    "CaveFinder",
    "OreESP",
    "NewChunks",
    "ChunkBorders",
    "TunnelFinder",
    "TargetHUD",
    "ReachDisplay",
    "DoubleClicker",
    "JitterClick",
    "ButterflyClick",
    "CPSBoost",
    "ChestStealer",
    "InvManager",
    "InvMovebypass",
    "AutoSprint",
    "AntiAFK",
    "AutoRespawn",
    "PopSwitch",
    "FakeLatency",
    "FakePing",
    "SpoofRotation",
    "PositionSpoof",
    "GameSpeed",
    "SpeedTimer",
    "GrimBypass",
    "VulcanBypass",
    "MatrixBypass",
    "AACBypass",
    "VerusDisabler",
    "IntaveBypass",
    "WatchdogBypass",
    "PacketMine",
    "PacketWalk",
    "PacketSneak",
    "PacketCancel",
    "PacketDupe",
    "PacketSpam",
    "SelfDestruct",
    "HideClient",
    "SessionStealer",
    "TokenLogger",
    "TokenGrabber",
    "DiscordToken",
    "RemoteAccess",
    "ReverseShell",
    "C2Server",
    "Backdoor",
    "KeyLogger",
    "StashFinder",
    "TrailFinder",
    "imgui.binding",
    "JNativeHook",
    "GlobalScreen",
    "NativeKeyListener",
    "client-refmap.json",
    "cheat-refmap.json",
    "aHR0cDovL2FwaS5ub3ZhY2xpZW50LmxvbC93ZWJob29rLnR4dA==",
    "meteordevelopment",
    "cc/novoline",
    "com/alan/clients",
    "club/maxstats",
    "wtf/moonlight",
    "me/zeroeightsix/kami",
    "net/ccbluex",
    "today/opai",
    "net/minecraft/injection",
    "org/chainlibs/module/impl/modules",
    "xyz/greaj",
    "com/cheatbreaker",
    "com/moonsworth",
    "doomsdayclient",
    "DoomsdayClient",
    "doomsday.jar",
    "novaclient",
    "api.novaclient.lol",
    "vape.gg",
    "vapeclient",
    "VapeClient",
    "VapeLite",
    "intent.store",
    "IntentClient",
    "rise.today",
    "riseclient.com",
    "meteor-client",
    "meteorclient",
    "meteordevelopment.meteorclient",
    "liquidbounce",
    "fdp-client",
    "net.ccbluex",
    "novoware",
    "novoclient",
    "aristois",
    "impactclient",
    "azura",
    "pandaware",
    "skilled",
    "moonClient",
    "astolfo",
    "futureClient",
    "konas",
    "rusherhack",
    "inertia",
    "exhibition",
    "dev.krypton",
    "dev/krypton",
    "skid.krypton",
    "skid/krypton",
    "VirginClient",
    "virgin client",
    "CatleanClient",
    "catlean client",
    "ArgonClient",
    "argon client",
    "Asteria",
    "AsteriaClient",
    "asteria client",
    "Prestige",
    "PrestigeClient",
    "prestige client",
    "prestigeclient.vip",
    "gypsy",
    "GypsyClient",
    "gypsy client",
    "Xenon",
    "XenonClient",
    "xenon client",
    "GrimClient",
    "grim client",
    "phantom-refmap.json",
    "dqrkis.xyz",
};

inline const std::vector<std::string> jarNamePatterns = {
    "AimAssist",
    "AnchorTweaks",
    "AutoAnchor",
    "AutoCrystal",
    "AutoDoubleHand",
    "JDWP.VirtualMachine.AllModules",
    "AutoHitCrystal",
    "AutoPot",
    "AutoTotem",
    "AutoArmor",
    "InventoryTotem",
    "LegitTotem",
    "PingSpoof",
    "SelfDestruct",
    "ShieldBreaker",
    "TriggerBot",
    "AxeSpam",
    "WebMacro",
    "FastPlace",
    "WalskyOptimizer",
    "WalksyOptimizer",
    "walsky.optimizer",
    "WalksyCrystalOptimizerMod",
    "Donut",
    "Replace Mod",
    "ShieldDisabler",
    "SilentAim",
    "Totem Hit",
    "Wtap",
    "FakeLag",
    "BlockESP",
    "dev.krypton",
    "dev/krypton",
    "skid.krypton",
    "skid/krypton",
    "AntiMissClick",
    "LagReach",
    "PopSwitch",
    "SprintReset",
    "ChestSteal",
    "AntiBot",
    "ElytraSwap",
    "FastXP",
    "FastExp",
    "Refill",
    "AirAnchor",
    "jnativehook",
    "FakeInv",
    "HoverTotem",
    "AutoClicker",
    "AutoFirework",
    "PackSpoof",
    "Antiknockback",
    "catlean",
    "AuthBypass",
    "Asteria",
    "Prestige",
    "AutoEat",
    "AutoMine",
    "MaceSwap",
    "Macro198",
    "StunSlam",
    "SafeAnchor",
    "DoubleAnchor",
    "AutoTPA",
    "BaseFinder",
    "Xenon",
    "gypsy",
    "AutoPotRefill",
    "KeyPearl",
    "AutoNethPot",
    "AutoDtap",
    "AutoWeb",
    "AnchorAction",
    "org.chainlibs.module.impl.modules.Crystal.Y",
    "org.chainlibs.module.impl.modules.Crystal.bF",
    "org.chainlibs.module.impl.modules.Crystal.bM",
    "org.chainlibs.module.impl.modules.Crystal.bY",
    "org.chainlibs.module.impl.modules.Crystal.bq",
    "org.chainlibs.module.impl.modules.Crystal.cv",
    "org.chainlibs.module.impl.modules.Crystal.o",
    "org.chainlibs.module.impl.modules.Blatant.I",
    "org.chainlibs.module.impl.modules.Blatant.bR",
    "org.chainlibs.module.impl.modules.Blatant.bx",
    "org.chainlibs.module.impl.modules.Blatant.cj",
    "org.chainlibs.module.impl.modules.Blatant.dk",
    "imgui.gl3",
    "imgui.glfw",
    "BowAim",
    "Criticals",
    "Fakenick",
    "FakeItem",
    "invsee",
    "ItemExploit",
    "Hellion",
    "hellion",
    "LicenseCheckMixin",
    "ClientPlayerInteractionManagerAccessor",
    "ClientPlayerEntityMixim",
    "dev.gambleclient",
    "obfuscatedAuth",
    "phantom-refmap.json",
    "xyz.greaj",
};

